//~~~~~~~~~~~~~~~~~~~~~~~~~Consts / Typedefs / Enums~~~~~~~~~~~~~~~~~~~~~~~~~//

/*/~~~~~Typedefs~~~~~/*/
typedef const int DEFINE;
typedef const int CONFIG;
typedef const bool CONFIGB;

CONFIGB DEBUG = true; // TODO disable for final release

/*/~~~~~Global Variables~~~~~/*/
bool disableTrans;

bool levelEntries[512];

int onContHP = 0;
int onContMP = 0;
int gameframe = 0;
int lastPal = -1;

bitmap waterfallBitmap;

int stolenLinkItems[255];

bool auriVillageMusicSet = false;

bool elevatorsAtHome[5] = {true, true, true, true, true};

/*/~~~~~Magnitude~~~~~/*/
CONFIG INTRO_SCENE_TRANSITION_MULT = 8;
CONFIG INTRO_SCENE_TRANSITION_FRAMES = 32;

CONFIG SUB_COOLDOWN_TILE_WIDTH = 9;

/*/~~~~~Item Classes~~~~~/*/
DEFINE IC_GALEBRANG = IC_CUSTOM1;

/*/~~~~~Combo~~~~~/*/
CONFIG CMB_INVIS = 1;

CONFIG COMBO_L = 7744;
CONFIG COMBO_R = 7745;

/*/~~~~~Tile~~~~~/*/
CONFIG TILE_INVIS = 4; //was 196

CONFIG TILE_IMPACT_MID = 955;
CONFIG TILE_IMPACT_BIG = 952;

CONFIG SUB_COOLDOWN_TILE = 29281;

/*/~~~~~Enums~~~~~/*/

enum Item {
   ITEM_RUPEE_1 = 0,
   ITEM_RUPEE_5 = 1,
   ITEM_RUPEE_10 = 86,
   ITEM_RUPEE_20 = 38,
   ITEM_RUPEE_50 = 39,
   ITEM_RUPEE_100 = 87,
   ITEM_RUPEE_200 = 40,
   ITEM_HEART_1 = 2,
   ITEM_HEART_3 = 114,
   ITEM_HEART_5 = 165,
   ITEM_HEART_PIECE = 49,
   ITEM_HEART_CONTAINER = 28,
   ITEM_BOMB1 = 3,
   ITEM_BOMB2 = 48,
   ITEM_BOMB3 = 236,
   ITEM_BOMB_AMMUNITION_1 = 77,
   ITEM_BOMB_AMMUNITION_4 = 78,
   ITEM_BOMB_AMMUNITION_8 = 79,
   ITEM_BOMB_AMMUNITION_30 = 80,
   ITEM_BOMB_BAG_SMALL = 81,
   ITEM_SWORD1 = 5,
   ITEM_SWORD2 = 6,
   ITEM_SWORD3 = 7,
   ITEM_SWORD4 = 36,
   ITEM_SWORD5 = 220,
   ITEM_SWORD6 = 144,
   ITEM_SHIELD1 = 93,
   ITEM_SHIELD2 = 8,
   ITEM_SHIELD3 = 37,
   ITEM_SHIELD4 = 54,
   ITEM_CANDLE1 = 158,
   ITEM_CANDLE2 = 10,
   ITEM_CANDLE3 = 11,
   ITEM_CANDLE4 = 150,
   ITEM_BRANG1 = 23,
   ITEM_BRANG2 = 24,
   ITEM_BRANG3 = 35,
   ITEM_BRANG4 = 146,
   ITEM_ARROW1 = 13,
   ITEM_ARROW2 = 14,
   ITEM_ARROW3 = 57,
   ITEM_ARROW4 = 153,
   ITEM_ARROW5 = 154,
   ITEM_ARROW_AMMUNITION_1 = 70,
   ITEM_ARROW_AMMUNITION_5 = 71,
   ITEM_ARROW_AMMUNITION_10 = 72,
   ITEM_ARROW_AMMUNITION_30 = 73,
   ITEM_BOW1 = 15,
   ITEM_BOW2 = 68,
   ITEM_BOW3 = 151,
   ITEM_RING1 = 17,
   ITEM_RING2 = 18,
   ITEM_RING3 = 61,
   ITEM_RING4 = 219,
   ITEM_RING5 = 145,
   ITEM_BRACELET1 = 107,
   ITEM_BRACELET2 = 19,
   ITEM_BRACELET3 = 56,
   ITEM_LANTERN1 = 208,
   ITEM_LANTERN2 = 198,
   ITEM_LANTERN3 = 200,
   ITEM_LANTERN4 = 201,
   ITEM_POTION1 = 29,
   ITEM_POTION2 = 30,
   ITEM_POTION3 = 123,
   ITEM_WAND1 = 25,
   ITEM_WAND2 = 152,
   ITEM_HAMMER1 = 147,
   ITEM_HAMMER2 = 148,
   ITEM_HAMMER3 = 149,
   ITEM_HAMMER_AND_QUAKE = 167,
   ITEM_FLIPPERS1 = 51,
   ITEM_FLIPPERS2 = 199,
   ITEM_HOOKSHOT1 = 52,
   ITEM_HOOKSHOT2 = 89,
   ITEM_WALLET1 = 41,
   ITEM_WALLET2 = 42,
   ITEM_OCARINA1 = 31,
   ITEM_OCARINA2 = 166,
   ITEM_RAFT = 26,
   ITEM_LADDER = 27,
   ITEM_MEDICINAL_HERB = 12,
   ITEM_SEARED_STEAK = 16,
   ITEM_MAP = 21,
   ITEM_COMPASS = 22,
   ITEM_LENS_OF_TRUTH = 53,
   ITEM_MAGIC_CONTAINER = 58,
   ITEM_MAGIC_JAR_SMALL = 59,
   ITEM_MAGIC_JAR_LARGE = 60,
   ITEM_DINS_FIRE = 64,
   ITEM_FARORES_WIND = 65,
   ITEM_NAYRUS_LOVE = 66,
   ITEM_KEY_BOSS = 67,
   ITEM_QUIVER1_SMALL = 74,
   ITEM_KEY_LEVEL = 84,
   ITEM_CANE1 = 88,
   ITEM_SCROLL_SPIN_ATTACK = 94,
   ITEM_SCROLL_CROSS_BEAMS = 95,
   ITEM_SCROLL_QUAKE_HAMMER = 96,
   ITEM_SCROLL_SUPER_QUAKE_HAMMER = 97,
   ITEM_SCROLL_HURRICANE_SPIN = 98,
   ITEM_WHISP_RING1 = 99,
   ITEM_WHISP_RING2 = 100,
   ITEM_CHARGE_RING1 = 101,
   ITEM_CHARGE_RING2 = 102,
   ITEM_SCROLL_PERIL_BEAM = 103,
   ITEM_WEALTH_MEDAL1 = 109,
   ITEM_WEALTH_MEDAL2 = 110,
   ITEM_WEALTH_MEDAL3 = 111,
   ITEM_HEART_RING1 = 112,
   ITEM_HEART_RING2 = 113,
   ITEM_HEART_RING3 = 223,
   ITEM_HEART_RING4 = 224,
   ITEM_HEART_RING5 = 225,
   ITEM_MAGIC_RING1 = 115,
   ITEM_MAGIC_RING2 = 116,
   ITEM_MAGIC_RING3 = 117,
   ITEM_MAGIC_RING4 = 118,
   ITEM_MAGIC_RING5 = 221,
   ITEM_MAGIC_PICKUP = 222,
   ITEM_PERIL_RING = 121,
   ITEM_WHIMSICAL_RING = 122,
   ITEM_HAERENS_GRACE = 124,
   ITEM_GANONS_RAGE = 125,
   ITEM_HEROS_ARMOR = 126,
   ITEM_SCHOLARS_MIND = 127,
   ITEM_DEATHS_AURA = 128,
   ITEM_CANE2 = 129,
   ITEM_LEGIONNAIRE_RING = 130,
   ITEM_PORTAL_SPHERE = 143,
   ITEM_STRANGE_COFFER = 155,
   ITEM_REALLY_SMALL_KEY = 156,
   ITEM_ENGAGEMENT_RING = 157,
   ITEM_BOSS_HEALTH_BARS = 159,
   ITEM_JEWEL_OF_MARRE = 171,
   ITEM_PIRATE_TOME = 177,
   ITEM_MYSTERIOUS_ZORA_CHARM = 178,
   ITEM_ANCIENT_TABLET_PIECE = 182,
   ITEM_LEVIATHAN_SCALE1 = 183,
   ITEM_LEVIATHAN_SCALE2 = 218,
   ITEM_CUMPURA_KEY = 184,
   ITEM_TRADING1_SPECIAL_MUSHROOM = 185,
   ITEM_EXPANSION_BOMB = 186,
   ITEM_RAFT_ANCIENT_HERO = 189,
   ITEM_BATTLE_ARENA_TICKET = 191,
   ITEM_TRADING2_PERFECT_LEAF = 192,
   ITEM_TRADING3_LADYS_BOW = 193,
   ITEM_ROCK_PROJECTILE = 195,
   ITEM_BOULDER_PROJECTILE = 196,
   ITEM_RACCOON_PROJECTILE = 197,
   ITEM_GUARD_TOWER_KEY = 202,
   ITEM_ARROW_AND_QUIVER = 203,
   ITEM_ARROW_PROJECTILE = 204,
   ITEM_EXPANSION_QUIVER = 205,
   ITEM_SIGNET_OF_ALLEGIANCE = 206,
   ITEM_MYSTERIOUS_KEY = 207,
   ITEM_TRIFORCE_SHARD_COURAGE = 209,
   ITEM_TRIFORCE_SHARD_WISDOM = 210,
   ITEM_TRIFORCE_SHARD_POWER = 211,
   ITEM_TRIFORCE_SHARD_DEATH = 212,

   ITEM_SUMMUS_TABLET_SHARD_A = 182,
   ITEM_SUMMUS_TABLET_SHARD_B = 215,
   ITEM_SUMMUS_TABLET_SHARD_C = 216,
   ITEM_SUMMUS_TABLET_SHARD_D = 217,

   ITEM_DIFFICULTY_VERY_EASY = 163,
   ITEM_DIFFICULTY_EASY = 160,
   ITEM_DIFFICULTY_NORMAL = 161,
   ITEM_DIFFICULTY_HARD = 162,
   ITEM_DIFFICULTY_VERY_HARD = 164
};

enum Sfx {
   SFX_SWITCH_RELEASE = 0, // SFX when a switch is released
   SFX_SUPER_JUMP = 0, //TODO set these
   SFX_SLAM = 0,

   SFX_BOMB_BLAST = 3,
   SFX_SWORD_ROCK3 = 6,
   SFX_OOT_SECRET = 7,
   SFX_ROCKINGSHIP = 9,
   SFX_FLAMMING_ARROW = 13,
   SFX_SWITCH_PRESS = 17,
   SFX_MIRROR_SHIELD_ABSORB_LOOP = 60,
   SFX_POWDER_KEG_BLAST = 61,
   SFX_SWITCH_ERROR = 62,
   SFX_SUMMON_MINE = 64,
   SFX_ONOX_TORNADO = 63,
   SFX_COMPASS_BEEP = 69,
   SFX_OOT_ARMOS_DIE = 73,
   SFX_OOT_BIG_DEKU_BABA_LUNGE = 75,
   SFX_IRON_KNUCKLE_STEP = 79,
   SFX_OOT_STALFOS_DIE = 104,
   SFX_SHOOTSWORD = 127,
   SFX_SIZZLE = 128,
   SFX_LAUNCH_BOMBS = 129,
   SFX_ARIN_SPLAT = 131,
   SFX_SQUISH = 138,
   SFX_OOT_WHISTLE = 143,
   SFX_AXE2 = 145,
   SFX_MC_BOUNDCHEST_ROAR1 = 146,
   SFX_MC_BOUNDCHEST_ROAR2 = 147,
   SFX_GOMESS_DIE = 148,
   SFX_MC_BOUNDCHEST_ROAR1AND2 = 149,
   SFX_IRON_KNUCKLE_HIT = 150,
   SFX_SHUTTER_OPEN = 151,
   SFX_SHUTTER_CLOSE = 152,
   SFX_IRON_KNUCKLE_ATTACK = 153,
   SFX_IRON_KNUCKLE_ATTACK_SWIPE = 154,

   SFX_HERO_HURT_1 = 157,
   SFX_HERO_HURT_2 = 158,
   SFX_HERO_HURT_3 = 159,
   SFX_HERO_HURT_4 = 180,
   SFX_HERO_HURT_5 = 181,
   SFX_HERO_HURT_6 = 182,

   SFX_SIGHTED = 161,
   SFX_WATER_DRIPPING = 165,
   SFX_STALFOS_GROAN = 166,
   SFX_STALFOS_GROAN_FAST = 167,
   SFX_STALFOS_GROAN_SLOW = 168,
   SFX_IMPACT_EXPLOSION = 169,
   SFX_STALCHILD_ATTACK = 170,

   SFX_SM_ELEVATOR_LOOP = 184,

   SFX_CURSOR_MOVEMENT = 5,
   SFX_SELECTION = 66
};

enum Sprite {
   SPR_LEGIONNAIRESWORD = 110,
   SPR_POISON_CLOUD = 111,
   SPR_FOOTSTEP = 113,

   SPR_EZB_DEATHEXPLOSION = 0, // Sprite to use for death explosions (0 for ZC default)
   EZB_DEATH_FLASH = 1,        // Set to 1 to make the enemy flash during death animations

   SPR_FLAME_TRAIL = 123,

   SPR_ROTATING_PILLAR = 57,

   SPR_FLAME_WAX = 35,
   SPR_FLAME_OIL = 142,
   SPR_FLAME_INCENDIARY = 144,
   SPR_FLAME_HELLS = 146,
   SPR_FLAME_WAX2X2 = 141,
   SPR_FLAME_OIL2X2 = 143,
   SPR_FLAME_INCENDIARY2X2 = 145,
   SPR_FLAME_HELLS2X2 = 147,

   SPR_ENEMY_FLAME_WAX = 35,
   SPR_ENEMY_FLAME_OIL = 142,
   SPR_ENEMY_FLAME_INCENDIARY = 144,
   SPR_ENEMY_FLAME_HELLS = 146,
   SPR_ENEMY_FLAME_WAX2X2 = 141,
   SPR_ENEMY_FLAME_OIL2X2 = 143,
   SPR_ENEMY_FLAME_INCENDIARY2X2 = 145,
   SPR_ENEMY_FLAME_HELLS2X2 = 147,

   SPR_SMALL_ROCK = 118,
   SPR_SUPER_SMALL_ROCK = 18,

   SPR_WHIRLWIND = 13
};

enum Counters {
   CR_TRIFORCE_OF_COURAGE = CR_CUSTOM1, // 7
   CR_TRIFORCE_OF_POWER = CR_CUSTOM2,   // 8
   CR_TRIFORCE_OF_WISDOM = CR_CUSTOM3,  // 9
   CR_TRIFORCE_OF_DEATH = CR_CUSTOM4,   // 10
   CR_LEGIONNAIRE_RING = CR_CUSTOM5,    // 11
   CR_HEARTPIECES = CR_CUSTOM6,         // 12
   CR_MAGIC_EXPANSIONS = CR_CUSTOM7,    // 13
   CR_BOMB_BAG_EXPANSIONS = CR_CUSTOM8, // 14
   CR_QUIVER_EXPANSIONS = CR_CUSTOM9,   // 15
   CR_MAGIC_RING_SHARDS = CR_CUSTOM10,   // 16
   CR_HEART_RING_SHARDS = CR_CUSTOM11   // 17
};

enum Enemy {
   ENEMY_OCTOROCK_LV1_SLOW = 20,
   ENEMY_OCTOROCK_LV1_FAST = 22,
   ENEMY_OCTOROCK_LV2_SLOW = 21,
   ENEMY_OCTOROCK_LV2_FAST = 23,

   ENEMY_MOBLIN_LV1 = 28,
   ENEMY_MOBLIN_LV2 = 29,

   ENEMY_STALFOS_LV1 = 41,
   ENEMY_STALFOS_LV2 = 79,

   ENEMY_ROPE_LV1 = 44,
   ENEMY_ROPE_LV2 = 80,

   ENEMY_GORIYA_LV1 = 45,
   ENEMY_GORIYA_LV2 = 46,

   ENEMY_ARMOS_LV1 = 37,
   ENEMY_ARMOS_LV2 = 179,

   ENEMY_LEEVER_LV1_INSIDE = 190,
   ENEMY_LEEVER_LV2_INSIDE = 27,

   ENEMY_BAT = 198,

   ENEMY_THIEF_LV1 = 213,
   ENEMY_THIEF_LV2 = 214,

   ENEMY_CANDLEHEAD_LV1 = 237,
   ENEMY_CANDLEHEAD_CHUNGO = 238,

   ENEMY_ZOMBIE_LV1 = 222,
   ENEMY_ZOMBIE_LV1_POPUP = 225,
   ENEMY_ZOMBIE_LV1_SPRINTING = 228,
   ENEMY_ZOMBIE_LV3 = 224,

   ENEMY_GHINI_SERVUS_SUMMON = 243,

   ENEMY_LEGIONNAIRE_LVL1 = 220,
   ENEMY_LEGIONNAIRE_LVL3 = 272,

   ENEMY_SOLDIER_LEVEL2 = 205,
   ENEMY_SOLDIER_LEVEL2_HALTED = 255,

   ENEMY_BUBBLE_TEMP_LV1 = 118,
   ENEMY_BUBBLE_TEMP_LV2 = 251,

   ENEMY_GRAVE_KEEPER_GONE_APE = 259,

   ENEMY_OVERGROWN_RACCOON = 235,
   ENEMY_THIEF_BOSS = 263
};

enum Color {
   C_TRANSBG = -1,
   C_TRANS = 0x00,
   C_GREEN = 0x06,
   C_DARKGREEN = 0x07,
   C_BLACK = 0x08,
   C_RED = 0x04,
   C_WHITE = 0x0C,
   C_BLUE = 0x1F,
   C_GRAY = 0x29,
   C_LGRAY = 0x59,
   C_DGRAY = 0x5A,
   C_TAN = 0x75,
   C_SEABLUE = 0x76,
   C_DARKBLUE = 0x77,
   C_DEEPBLUE = 0x1F
};

enum ScreenType {
   DM_DUNGEON,
   DM_OVERWORLD,
   DM_INTERIOR,
   DM_BSOVERWORLD
};

enum ArcingWeaponEffects {
   AE_NONE,
   // Shambles
   AE_BOMB,
   AE_SMALLPOISONPOOL,
   AE_LARGEPOISONPOOL,
   AE_PROJECTILE_WITH_MOMENTUM,

   // Hazarond
   AE_OIL_BLOB,
   AE_OIL_DEATH_BLOB,

   // Overgrown Raccoon
   AE_ROCK_PROJECTILE,
   AE_BOULDER_PROJECTILE,
   AE_RACCOON_PROJECTILE,

   // Egentem
   AE_EGENTEM_HAMMER,

   // Misc
   AE_BOMB_EXPLOSION,
   AE_ARROW,

   AE_DEBUG
};